DROP TABLE TREATMENT_TABLE;
DROP TABLE BILLING_TABLE;
DROP TABLE MEDICINE_TABLE;
DROP TABLE DISEASE_TABLE;
DROP TABLE STAFF_TABLE;
DROP TABLE VETERINARIAN_TABLE;
DROP TABLE SPECIALITY_TABLE;
DROP TABLE ANIMAL_TABLE;
DROP TABLE CUSTOMER_TABLE;

CREATE TABLE CUSTOMER_TABLE (

  CUSTOMER_ID VARCHAR(6),
  FIRST_NAME  VARCHAR(50),
  SURNAME     VARCHAR(50),
  CONTACT     VARCHAR(30),
  EMAIL       VARCHAR(30),
  CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY (CUSTOMER_ID)

);

CREATE TABLE ANIMAL_TABLE (

  ANIMAL_ID     VARCHAR(4),
  ANIMAL_TYPE   VARCHAR(30),
  ANIMAL_BREED  VARCHAR(30),
  ANIMAL_COLOUR VARCHAR(30),
  CONSTRAINT PK_ANIMAL_ID PRIMARY KEY (ANIMAL_ID)

);

CREATE TABLE SPECIALITY_TABLE (

  SPECIALTY_ID INT,
  SPECIALITY   VARCHAR(30),
  CONSTRAINT PK_SPECAILITY_ID PRIMARY KEY (SPECIALTY_ID)


);

CREATE TABLE VETERINARIAN_TABLE (

  VET_ID        VARCHAR(4),
  FIRST_NAME    VARCHAR(50),
  SURNAME       VARCHAR(50),
  CONTACT       VARCHAR(30),
  EMAIL         VARCHAR(30),
  SPECIALITY_ID INT,
  CONSTRAINT PK_VET_ID PRIMARY KEY (VET_ID),
  CONSTRAINT FK_SPECIALITY_ID FOREIGN KEY (SPECIALITY_ID) REFERENCES SPECIALITY_TABLE (SPECIALTY_ID)

);

CREATE TABLE STAFF_TABLE (

  STAFF_ID        VARCHAR(4),
  FIRST_NAME      VARCHAR(50),
  SURNAME         VARCHAR(50),
  JOB_DESCRIPTION VARCHAR(50),
  CONTACT         VARCHAR(30),
  CONSTRAINT PK_STAFF_ID PRIMARY KEY (STAFF_ID)

);

CREATE TABLE DISEASE_TABLE (

  DISEASE_ID   VARCHAR(9),
  DISEASE_NAME VARCHAR(50),
  CONSTRAINT PK_DISEASE_ID PRIMARY KEY (DISEASE_ID)

);

CREATE TABLE MEDICINE_TABLE (

  MED_ID          VARCHAR(9),
  MED_NAME        VARCHAR(50),
  MED_PRICE       NUMBER,
  MED_EXPIRY_DATE DATE,
  CONSTRAINT PK_MED_ID PRIMARY KEY (MED_ID)

);

CREATE TABLE BILLING_TABLE (

  BILL_ID     VARCHAR(9),
  CUSTOMER_ID VARCHAR(6),
  STAFF_ID    VARCHAR(4),
  BILL_HRS    NUMBER,
  CONSTRAINT PK_BILL_ID PRIMARY KEY (BILL_ID),
  CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_TABLE (CUSTOMER_ID),
  CONSTRAINT FK_STAFF_ID FOREIGN KEY (STAFF_ID) REFERENCES STAFF_TABLE (STAFF_ID)

);

CREATE TABLE TREATMENT_TABLE (

  TREATMENT_ID VARCHAR(8),
  ANIMAL_ID    VARCHAR(4),
  DISEASE_ID   VARCHAR(9),
  BILL_ID      VARCHAR(9),
  VET_ID       VARCHAR(4),
  MED_ID       VARCHAR(9),
  CONSTRAINT PK_TREATMENT_ID PRIMARY KEY (TREATMENT_ID),
  CONSTRAINT FK_ANIMAL_ID FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL_TABLE (ANIMAL_ID),
  CONSTRAINT FK_DISEASE_ID FOREIGN KEY (DISEASE_ID) REFERENCES DISEASE_TABLE (DISEASE_ID),
  CONSTRAINT FK_BILL_ID FOREIGN KEY (BILL_ID) REFERENCES BILLING_TABLE (BILL_ID),
  CONSTRAINT FK_VET_ID FOREIGN KEY (VET_ID) REFERENCES VETERINARIAN_TABLE (VET_ID),
  CONSTRAINT FK_MED_ID FOREIGN KEY (MED_ID) REFERENCES MEDICINE_TABLE (MED_ID)

);

